#!/usr/bin/env bash
{ set +x; } 2>/dev/null

set -- https://pypi.python.org/pypi/google-chrome
# close tab
[[ $OSTYPE != *darwin* ]] && echo "SKIP: OSX only" && exit 0

[[ $# == 0 ]] && [[ $1 == "--help" ]] && {
  cat <<EOF
usage: ${BASH_SOURCE[0]##*/} url
EOF
  exit 0
}

url="$1"
osascript <<EOF
tell application "Google Chrome"                   
  repeat with w in  every window
  set tab_i to 0
    repeat with t in every tab in w     
      set tab_i to (tab_i+1)
        if (URL of t) is "$url" then
          tell t to close
          return
        end if
      end repeat
  end repeat
end tell
EOF
