#!/usr/bin/env bash
{ set +x; } 2>/dev/null

# open/refresh url
[[ $OSTYPE != *darwin* ]] && echo "SKIP: OSX only" && exit 0

[[ $# == 0 ]] && [[ $1 == "--help" ]] && {
  cat <<EOF
usage: ${BASH_SOURCE[0]##*/} url
EOF
  exit 0
}

url="$1"
osascript <<EOF
tell application "Google Chrome"                   
  repeat with w in  every window
  set tab_i to 0
    repeat with t in every tab in w     
      set tab_i to (tab_i+1)
        if (URL of t) is "$url" then
          --tell t to reload
          --use google-chrome-refresh to refresh
          set index of w to 1 --activate window
          tell w to set active tab index to tab_i --activate tab
          return
        end if
      end repeat
  end repeat
  open location "$url"
end tell
EOF
